pipeline {
  agent any
  stages {
    stage('Back-end') {
      steps {
        sh 'wget -qO- https://apache.osuosl.org/maven/maven-3/3.8.3/binaries/apache-maven-3.8.3-bin.tar.gz | tar xvz -C /tmp'
        sh 'export PATH=/tmp/apache-maven-3.8.3/bin:$PATH'
        sh 'mvn --version' // Verify Maven installation
      }
    }
    stage('Front-end') {
      steps {
        sh 'node --version'
      }
    }
  }
}
